name: licitmokus_app
description: "Licitmokus – Firebase-based bidding app built with Flutter."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # UI & utilities
  flutter_svg: ^2.0.10
  cupertino_icons: ^1.0.8
  petitparser: 6.1.0

  # Firebase core services
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/bidsquarrel_main.svg
