# Base image: use lightweight NGINX for serving Flutter web app
FROM nginx:alpine

# Set working directory
WORKDIR /usr/share/nginx/html

# Clean the default nginx content
RUN rm -rf ./*

# Copy the Flutter web build from licitmokus_app
COPY ../packages/licitmokus_app/build/web/ .

# (Optional) Disable browser caching during dev
# RUN echo 'add_header Cache-Control "no-store";' >> /etc/nginx/conf.d/default.conf
