name: Build & Deploy Licitmokus App to GHCR

on:
  push:
    branches:
      - ci-*
      - feature/*

jobs:
  licitmokus-build-and-push:
    runs-on: ubuntu-latest
    name: Build & Push Docker Image for Licitmokus

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Flutter commands in official Docker image (Dart 3.7+ biztos!)
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/cirruslabs/flutter:stable
          options: -v ${{ github.workspace }}:/workspace -w /workspace
          run: |
            cd packages/licitmokus_app
            flutter pub get
            flutter build web

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: tjtamas
          password: ${{ secrets.GHCR_PAT }}

      - name: Build Docker image
        run: |
          docker build -f docker/Dockerfile.licitmokus -t ghcr.io/${{ github.repository_owner }}/licitmokus_web:latest .

      - name: Push Docker image to GHCR
        run: docker push ghcr.io/${{ github.repository_owner }}/licitmokus_web:latest
